In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import OneHotEncoder

In [2]:
image = np.random.rand(28, 28)  # Simula una imagen de 28x28
image

array([[9.75988318e-01, 6.54870511e-01, 8.42983382e-01, 6.31914324e-01,
        7.42638295e-01, 8.50477736e-01, 5.60740157e-01, 3.61602284e-01,
        8.32853606e-01, 4.62614971e-01, 3.68409749e-01, 1.70642878e-01,
        3.06058661e-01, 1.03913130e-02, 4.30714985e-03, 8.79315848e-01,
        8.20070398e-01, 6.82859299e-01, 1.08623156e-01, 4.77709194e-01,
        5.02983211e-02, 8.84204144e-01, 4.64194637e-01, 8.59110919e-01,
        7.69288955e-01, 2.24381178e-01, 7.44625394e-01, 4.85995173e-01],
       [4.16247317e-01, 1.53853337e-01, 5.91610860e-01, 3.08536676e-01,
        7.33972233e-01, 7.68826463e-01, 4.01455020e-01, 6.37910507e-01,
        8.26188530e-01, 9.25666094e-01, 7.93900895e-01, 5.79126932e-01,
        9.46242249e-01, 6.68054689e-01, 3.58701845e-01, 7.63990256e-01,
        3.48060590e-01, 2.76913281e-01, 2.08408343e-01, 6.45564178e-01,
        6.02529859e-01, 1.30329636e-01, 1.82101328e-01, 4.73585596e-01,
        4.71537183e-01, 2.60608522e-01, 7.91340561e-01, 2.86966

In [3]:
vectorized_image = image.flatten()  # Convierte la matriz en un vector de 784 elementos
vectorized_image

array([9.75988318e-01, 6.54870511e-01, 8.42983382e-01, 6.31914324e-01,
       7.42638295e-01, 8.50477736e-01, 5.60740157e-01, 3.61602284e-01,
       8.32853606e-01, 4.62614971e-01, 3.68409749e-01, 1.70642878e-01,
       3.06058661e-01, 1.03913130e-02, 4.30714985e-03, 8.79315848e-01,
       8.20070398e-01, 6.82859299e-01, 1.08623156e-01, 4.77709194e-01,
       5.02983211e-02, 8.84204144e-01, 4.64194637e-01, 8.59110919e-01,
       7.69288955e-01, 2.24381178e-01, 7.44625394e-01, 4.85995173e-01,
       4.16247317e-01, 1.53853337e-01, 5.91610860e-01, 3.08536676e-01,
       7.33972233e-01, 7.68826463e-01, 4.01455020e-01, 6.37910507e-01,
       8.26188530e-01, 9.25666094e-01, 7.93900895e-01, 5.79126932e-01,
       9.46242249e-01, 6.68054689e-01, 3.58701845e-01, 7.63990256e-01,
       3.48060590e-01, 2.76913281e-01, 2.08408343e-01, 6.45564178e-01,
       6.02529859e-01, 1.30329636e-01, 1.82101328e-01, 4.73585596e-01,
       4.71537183e-01, 2.60608522e-01, 7.91340561e-01, 2.86966437e-01,
      

5.El método 'One hot encoding' codifica categorías.

In [4]:
data = pd.DataFrame({'color': ['azul', 'rojo', 'verde', 'rojo']})

In [5]:
data

color
0   azul
1   rojo
2  verde
3   rojo

In [6]:
# Instanciar el codificador OneHotEncoder
encoder = OneHotEncoder(sparse_output=False) 
encoder

OneHotEncoder(sparse_output=False)

In [7]:
# Ajustar y transformar los datos
encoded = encoder.fit_transform(data[['color']])
encoded

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [8]:
# Crear un DataFrame con los resultados
encoded_df = pd.DataFrame(encoded, columns=encoder.categories_[0])

In [9]:

# Mostrar el DataFrame con las columnas codificadas
print(encoded_df)

   azul  rojo  verde
0   1.0   0.0    0.0
1   0.0   1.0    0.0
2   0.0   0.0    1.0
3   0.0   1.0    0.0


In [26]:
from sklearn.decomposition import PCA

X = np.random.rand(100, 5)
pca = PCA(n_components=2)
X_reduced = pca.fit_transform(X)
print(X_reduced.shape)  # (100,2)

(100, 2)


In [30]:
pd.DataFrame(X)

0         1         2         3         4
0   0.792343  0.357536  0.404999  0.612103  0.932241
1   0.063759  0.569635  0.345147  0.201065  0.954920
2   0.542258  0.847845  0.516854  0.207923  0.113977
3   0.832476  0.056404  0.161942  0.406687  0.543229
4   0.900401  0.456862  0.345810  0.787293  0.763776
..       ...       ...       ...       ...       ...
95  0.480640  0.324847  0.288092  0.010427  0.202340
96  0.214601  0.848849  0.328313  0.246388  0.416781
97  0.687041  0.555804  0.555378  0.727447  0.496235
98  0.240966  0.882484  0.979734  0.543662  0.841016
99  0.129662  0.652363  0.866413  0.162798  0.582098

[100 rows x 5 columns]

In [28]:
pca

PCA(n_components=2)

In [29]:
X_reduced

array([[-0.43523729, -0.01111186],
       [ 0.13951318, -0.60657304],
       [ 0.53022889,  0.23758445],
       [-0.34878348,  0.28725758],
       [-0.39960697,  0.20483525],
       [-0.11885144, -0.41841265],
       [-0.29538748,  0.54748654],
       [ 0.42130164, -0.06970051],
       [-0.57844272,  0.16040973],
       [ 0.06188435,  0.24905292],
       [ 0.0609747 , -0.42978224],
       [-0.46898771, -0.10539746],
       [ 0.44467884,  0.1626889 ],
       [-0.17908482, -0.02968973],
       [ 0.05104773, -0.23904963],
       [ 0.44675217, -0.05380124],
       [ 0.41750747, -0.00596581],
       [-0.11950866,  0.0642318 ],
       [-0.19016455,  0.53420339],
       [ 0.41474848, -0.06671652],
       [-0.44533514, -0.16803553],
       [ 0.40176512,  0.1031552 ],
       [ 0.38649697,  0.61814655],
       [ 0.08035151,  0.27629051],
       [ 0.05502669,  0.2056781 ],
       [ 0.02500914, -0.17076027],
       [ 0.49543711,  0.0437402 ],
       [ 0.12010828,  0.17415029],
       [ 0.35001405,

In [31]:
pd.DataFrame(X_reduced)

0         1
0  -0.435237 -0.011112
1   0.139513 -0.606573
2   0.530229  0.237584
3  -0.348783  0.287258
4  -0.399607  0.204835
..       ...       ...
95  0.275411  0.163457
96  0.506870 -0.153541
97 -0.131737  0.160204
98  0.114318 -0.495331
99  0.304044 -0.436790

[100 rows x 2 columns]